Algoritmo "Questão 05"
// 5) Fazer um programa que pergunte o salário de
// um funcionário e apresente este salário com um
// aumento de 15%.
Var
// Seção de Declarações das variáveis 
  Salario,Acrescimo: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva("Informe o valor do sálario:")
  Leia(Salario)
  
  Acrescimo<- Salario + (salario * 0.15)
  escreva("Valor do sálario co 15% de acrescimo: ", Acrescimo)
Fimalgoritmo