Algoritmo "Quesão 03"
// 3) Fazer um programa que pergunte um valor
// em Dólares e apresente o equivalente em Reais.
// Considere U$1,00 = R$1,72.
Var
// Seção de Declarações das variáveis 
 dolar, reais: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreva("Insira o valor de dólares:")
  Leia(dolar)
  
  reais <- dolar * 1.72
  
  escreva("O valor em reais equivale á: ", reais)
  

Fimalgoritmo